### ISSUE TITLE
Requests json

### ISSUE THREAD

**Issue by TheyTookMyName** [elevenchars/discorddelete#1]
It's asking for a module named requests, yet there is no module for it. Is it a dependency I am missing, or have I done something wrong?

**Comment by elevenchars** [comment]
In order to install the request library run `pip install requests`. If this does not work (most likely on windows) run `python -m pip install requests`. I am assuming you [have your path set up](https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7). Please let me know if you have any other issues
